### ISSUE TITLE
username as clientid 

### ISSUE THREAD

**Issue by ksaritek** [moquette-io/moquette#163]
a config for using username as client_id.
already mosquitto has a config like that

**Comment by andsel** [comment]
Hi @ksaritek could you give a pointer to the mosquitto config variable that enables this behaviour?
  Andrea

**Comment by windbender** [comment]
There was a recent merge which allowed the authentication to be based on both username and clientid. Obviously you could ignore either of them, but this might allow you to do what you need.

If this works for you can you close the ticket.   Otherwise can you describe your use case in more detail. why/how would this be helpful ?  In general the MQTT protocol has separated the username and clientID on a protocol level.  It should be possible to send clientid as username ON THE CLIENT.

**Comment by andsel** [comment]
Closed by PR #185 from @bemisguided
