### ISSUE TITLE
Authentication on DB storage 

### ISSUE THREAD

**Issue by mackristof** [moquette-io/moquette#177]
I need to implement authentication on sql database. I think to create : 

```
public class DBAuthenticator implements IAuthenticator {

    private final String jdbcUrl;
    private final String sqlQuery;

    public DBAuthenticator(String jdbcUrl, String sqlQuery){
        this.jdbcUrl = jdbcUrl;
        this.sqlQuery = sqlQuery;
    }

    @Override
    public boolean checkValid(String username, byte[] password) {
        // Check Username / Password in DB using sqlQuery
        return false;
    }
}
```

would you like to have pull request for this feature ?

**Comment by andsel** [comment]
Yes, could be great. Please cover it with a unit test that create an in
memory H2 store, create the desired schema and validate 2 test cases: one
with success credential, one with not successfull. That could be great!!
Thanks
 Andrea

**Comment by mackristof** [comment]
is it good to "hard code" DBAuthenticator constructor call [here](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/SimpleMessaging.java#L117) ?
or how to adapt code for giving parameters to constructor with [this](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/SimpleMessaging.java#L150)  ?

finally the question is : do you want I DBAuthenticator use IConfig for getting his own configuration ?

**Comment by windbender** [comment]
DBAuthenticator is a great idea.  Make sure that your passwords are not stored in the clear on the database.  If you'd like code which does salting and appropriate hashing I'm happy to contribute this:
Lines 32 to 93 in this file:   https://github.com/windbender/wildlife-camera-machine/blob/master/src/main/java/com/github/windbender/dao/HibernateUserDAO.java
it is MIT licensed.

If people are concerned with connect performance then reducing iterations is appropriate up to a point. The entire goal of password hashing is to make the cost of computing a hash expensive so that trying passwords is computationally expensive.

Another option here is to look into integrating one of the various java security/authentication/authorization frameworks.  for example:   http://shiro.apache.org

For example here is their "Authenticator" interface:
http://shiro.apache.org/static/1.2.4/apidocs/org/apache/shiro/authc/Authenticator.html

**Comment by mackristof** [comment]
@windbender I begin to implement DBAuthenticator with delegation of the choice for digest by configuration : https://github.com/mackristof/moquette/commit/cad1165071693b19c83b73c76dd9ec0c65713d64#diff-b2986be988f4a8480d9bba829c8bd187R34

my question is : can I put the conf parameters (driverClass, jdbcUrl, digest ... ) in moquette.conf ?

**Comment by andsel** [comment]
Hi @mackristof, for me it's ok, also to put the config in moquette.conf,
but prefix the variabiles with "authenticator.db." then your authenticator
implementation should be provided with the IConfig instance, to mkae this
you have to change the instantiation phase which uses reflection to create
the authenticators.

 Andrea

**Comment by andsel** [comment]
Integrated with PR #178
