### ISSUE TITLE
AbstractInterceptHandler doesn't work

### ISSUE THREAD

**Issue by tang7526** [moquette-io/moquette#203]
I have a class PublisherListener that extends AbstractInterceptHandler.
When I publish message using internalPublish function, I thought the onPublish in PublisherListener would work. But it doesn't work.
How the onPublish can work?

my code: 

``` java
public class testMqtt{

    private static Server server;
    public static void main(String[] args) {
        new Thread() {
            public void run() {
                try {
                    server = new Server();
                    File configFile = new File("./moquette.conf");
                    final IConfig config = new FilesystemConfig(configFile);
                    final List<? extends InterceptHandler> userHandlers = Arrays.asList(new PublisherListener());
                    server.startServer(config, userHandlers);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }.start();

        Thread.sleep(2000); // waiting for server

        PublishMessage msg = new PublishMessage();
        msg.setQos(QOSType.LEAST_ONE);
        msg.setTopicName("topic");
        ByteBuffer sendBuffer = ByteBuffer.wrap("body".getBytes());
        msg.setPayload(sendBuffer);
        server.internalPublish(msg);
    }
}

public class PublisherListener extends AbstractInterceptHandler {

    @Override
    public void onConnect(InterceptConnectMessage msg) {
        System.out.println("onConnect");
    }

    @Override
    public void onDisconnect(InterceptDisconnectMessage msg) {
        System.out.println("onDisconnect");
    }

    @Override
    public void onPublish(InterceptPublishMessage msg) {
        System.out.println("onPublish");
    }

    @Override
    public void onSubscribe(InterceptSubscribeMessage msg) {
        System.out.println("onSubscribe");

    }

    @Override
    public void onUnsubscribe(InterceptUnsubscribeMessage msg) {
        System.out.println("onUnsubscribe");
    }
}
```

**Comment by kevto** [comment]
It does work. `internalPublish` ignores all InterceptHandlers because `internalPublish` is only performed by the owner and therefore should be trusted and known where the message will end up to. This is also written in the javadoc of the `ProtocolProcessor`class.  [Link to javadoc](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/ProtocolProcessor.java#L434)

Handlers are only used if the message is handled by `processPublish` method of `ProtocolProcessor`. [Code](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/ProtocolProcessor.java#L426)

The way the handlers are being used. [Code](https://github.com/andsel/moquette/blob/master/broker/src/main/java/io/moquette/spi/impl/BrokerInterceptor.java#L76)

---

If you do want to test your new handler, I would suggest to use Apache Paho's `MqttClient`class and perform a subscribe and publish in a unit test. That's the only way to test your handler properly.
