### ISSUE TITLE
Use AtomicInteger for message counters

### ISSUE THREAD

**Issue by andsel** [moquette-io/moquette#227]
As described in comments of #212 by @windbender

**Comment by windbender** [comment]
should this be closed ?

I also dug a bit deeper and noticed:

```
    @Override
    public void incUsageCounter(MessageGUID guid) {
        IMessagesStore.StoredMessage storedMessage = m_persistentMessageStore.get(guid);
        storedMessage.incReferenceCounter();
        m_persistentMessageStore.put(guid, storedMessage);
    }

    @Override
    public void decUsageCounter(MessageGUID guid) {
        IMessagesStore.StoredMessage storedMessage = m_persistentMessageStore.get(guid);
        storedMessage.decReferenceCounter();
        m_persistentMessageStore.put(guid, storedMessage);
    }
```

What is the purpose of doing the "put" after the inc or dec ?  it seems that the object retrieved in the get will be their either way no ?  this is not a database this is a ConcurrentMap.  so the object returned IS the object in the map not a copy of it.

Likewise

```
    void removeStoredMessage(MessageGUID guid) {
```

has problems since ideally only a single thread should do the remove . As it's written two different threads could enter at the same time, both complete the conditionals, and then both attempt to do the 

```
            m_persistentMessageStore.remove(guid);
```

**Comment by andsel** [comment]
I removed the reference counting, prefer to copy the message data instead of sharing, it lowers the contention on shared data.
