### ISSUE TITLE
some sugestion

### ISSUE THREAD

**Issue by shuzhongling** [moquette-io/moquette#232]
i an using moquette in embedded mode now, i found its design is very elegance. i also has some question. 

1.   the newest version of mapdb is 3.0.2,  but moquette still use version 1.08, can you upgrade mapdb to version 3.0.2? i read mapdb document on its web [http://www.mapdb.org/doc/]), the document tell me that  the performance improve very very much.  
2.  when i used  moquette as a embedded broker, i can't found any method to desconnect the client who published some message to unauthorized topic. eg, when the publish authorize failed, i want to desconnect the client. 
3.  when use the  interface IAuthorizator, i want also check the paload of  PUBLISH messge, if the payload format is currupt, i want to disconnect the client. but in the IAuthorizator, i can't get the payload.
4.  i don't know how much is the concurrent connection thar only  one moquette instance can cover. 
thank you very much!

**Comment by andsel** [comment]
1) look at issue #140 
2) I don't think that missed authorize should drop the client connection, the MQTT specification doesn't mention anything about it.
3) It' wanted, the interceptor interface is meant just to notify the listener, not to make the processing logic pluggable, because that could break the protocol specification
4) I don't have any benchmark about it
