### ISSUE TITLE
Dependency injection

### ISSUE THREAD

**Issue by christopheblin** [moquette-io/moquette#28]
Hi,

my goal is to be able to use moquette with my own IAuthenticator.

What I think is necessary to achieve this :
- SimpleMessaging should not be a singleton anymore (pretty easy since it is only used by Server class)
- All the dependency of it should be injected instead of being created inside init method (ex: IAuthenticator)
- regroup all authentication stuff into a package

If you agree, I'd like to do that in my fork and then crate a PR.

Are you ok with that ?

**Comment by andsel** [comment]
Hi Christoph,
your goal is great and is one thing that has to be done in Moquette, but there are 2 things that aren't good.
- the first is that SimpleMessaging must to be singleton because is the piece that instantiate the input ring buffer and the protocol processor. The protocol processor is thought to be single threaded and can't share internal data structure (in future I plan to move to multithreaded but before the data structures has to be moved to functional data structures that don't require locking).
- the second is that the authentication part has to be done out of the main protocol processor loop, else it will stall the overall processing (plan to integrate external plugins).

Andrea

**Comment by christopheblin** [comment]
With my impl, SimpleMessaging is still a singleton by the fact that it is instanciated only once.
Also, it is still SimpleMEssaging that instanciate the ring buffer and the processor.

The authentication is still done outside the main protocol : there is no change in that either.

The only thing that change is that authenticator is instanciated before SimpleMessaging so that I can give another impl to it.

So could you give extra explantion please

**Comment by andsel** [comment]
Moquette is intended to be used also as library to be integrated inside other projects. Invoking a constructor only one time doesn't mean it's a singleton, singleton meas that only one instance of the Moquette broker is instantiated per JVM, so the constructor invoked one time is not a good check.

The authentication has to be done in a separate thread of the main protocol processor thread. Suppose you a have implemented a Authenticator that use a Rest API to authenticate the user, or also a plain JDBC. Beeing the protocol processor single threaded, and it'has to process the HTTP request it meas that you stole time the main event loop, so you have to do it a secondary worker thread. I hope i was able to explain the motivation, if you have any other suggestions or questions please open a thread on the google groups, so that other interested people could follow the discussion.

 Regards
  Andrea
