### ISSUE TITLE
java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.readRetainedSlice(I)Lio/netty/buffer/ByteBuf

### ISSUE THREAD

**Issue by VledicFranco** [moquette-io/moquette#335]
When setting up an embedded server and trying to publish the service, it silently fails with this error and no stack trace for the exception. :P

```
[nioEventLoopGroup-3-2] INFO io.moquette.spi.impl.ProtocolProcessor - The CONNECT message has been processed. CId=7f000001dff959677f1e, username=null
[nioEventLoopGroup-3-2] ERROR io.moquette.server.netty.NettyMQTTHandler - An unexpected exception was caught while processing MQTT message. Closing Netty channel. CId=7f000001dff959677f1e, cause=java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.readRetainedSlice(I)Lio/netty/buffer/ByteBuf;, errorMessage=java.lang.NoSuchMethodError: io.netty.buffer.ByteBuf.readRetainedSlice(I)Lio/netty/buffer/ByteBuf;
```

**Comment by andsel** [comment]
This sound like there is any Netty dependencies is broken. Moquette uses 4.1.12.Final perhaps the embedding code force to a different version (in this mvn dependency:tree on your project should help understand)?
Do you have runnable code that expose the bug and share it so that I could reproduce by myself and fix it?

**Comment by nMoncho** [comment]
We'd some issues with the dependencies brought by a third library. You can probably close this issue to don't pollute the issues list.

cc: @FrancoAra please confirm ;)

**Comment by andsel** [comment]
No feedback from reporter, I close the issue, in case reopen it pls.
