### ISSUE TITLE
about giving up cluster and client load balance on 0.12

### ISSUE THREAD

**Issue by BEWINDOWEB** [moquette-io/moquette#451]
Hi andsel, I'm using moquette v0.12 and i have some questions.
1、May i ask why version 0.12 gives up cluster? Single server could not afford large request, there should be a lot of brokers to work together.
2、May i ask why moquette 0.10 uses hazelcast instead of using redis cluster? Is there something special for using hazelcast.

And i think mqtt broker should have these base function:
1. support cluster : like EMQ, do routing instead of broadcast
2. support client load balance : like EMQ3.0, because other service almost using WORKERS. one message should be send to one worker of a cosume group.

is there any other way to do this based on v0.12? 

It would be great if you could write down some reply, thanks.

**Comment by andsel** [comment]
1. I gave up the cluster because was poorly implemented, used Hazelcast only as message bus and the dependency on Hz bring 6Mb to the overall jars
2. Because with Hz was selfcontained, I dont' want the broker dependes on other services to be installed separately on the machines, the spriti is "download, run moquette.sh and play"

With version 0.12 at the moment you can't, and the development focus in to produce an MQTT v5 complaint implementattion
