### ISSUE TITLE
Please update h2-mvstore to latest version

### ISSUE THREAD

**Issue by joehei** [moquette-io/moquette#456]
### Expected behavior
Please update h2-mvstore to latest version. 1.4.198

### Actual behavior
I' also using H2 in my application but can not update to latest version because the version contained in moquette has in issue with the latest version. Both versions on the classpath can cause issues.

### Steps to reproduce
Create a Project using a h2 database with the latest version and a using an emedded moquette broker.

### Moquette MQTT version
0.12.1

### JVM version (e.g. `java -version`)
11.0.2

### OS version (e.g. `uname -a`)
Windows

**Comment by andsel** [comment]
I'll update, but this issue is the setup of your build tool, in it when import the Moqutte dependency, you should force to exclude to import transitively the Moquette's H2 version, for Maven you could read  it hear https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by andsel** [comment]
I update to version 1.4.199 because the 1.4.198 introduced a regression.
commit f3faee6fbe29400a4852e5925cecb370ad2380db
