### ISSUE TITLE
The "clientId" will be removed when the mobile client reconnect

### ISSUE THREAD

**Issue by yeongher** [moquette-io/moquette#71]
The network is unstable when the client runned at mobile phone,  the mqtt client will be reconnect repeatedly, but the old connection will be colsed lead to the "ProtocolProcessor" removes the cliendId.

As a result, the new message cannot arrive to the new connection.

**Comment by andsel** [comment]
Could you specify better, because when the client disconnects or get
disconnected by the broker because ping req doesn't happen in certain time,
the broker drop client data if not specified with cleanSession=false.  What
do you intend that the message cannot arrive?
Please give more details when you open a a bug report.

 Andrea

**Comment by andsel** [comment]
No news and no details, so I close the issue.

**Comment by esistgut** [comment]
Seems related to #4
