### ISSUE TITLE
New plugin manager with native JDK code

### ISSUE THREAD

**Issue by WilliamKinaan** [moquette-io/moquette#80]
Hi Andsel, 

I have changed the plugin manager to a native JDK code.

You can find the code here

https://github.com/WilliamKinaan/moquette/tree/plugin_native

Could you check please before I made a pull request? 

When you agree on the structure, i can add many plugins.

Many thanks in advance.
Best regards,

**Comment by andsel** [comment]
Hi William,
as I said before, I've already integrated the PR from Wagner to the master, so I don't intend to switch to another, so please if you want I review something, start from the current code base in the master.
Then when you modify files and want to contribute back, don't touch the complete indentation of a file (like in the ProtocolProcessor or Server in your branch) because understanding the diffs becomes really time wasting. 
 Please for any other discussion on funtionalities or architecture stuff that you want to discuss refer to the Google Group, this is an issue tracker not a chat.
I hope you could agree on these lines, many thanks

  Andrea

**Comment by WilliamKinaan** [comment]
Hi Andsel

I can open a discussion on Google group, but really there is no difference
in Server or Protocol classes, it is a very small difference, in the server
just one line code, and in the protocol class, just calling the methods,

it is a minimum changes as you wanted.

I hope we find something in common between us as we are doing efforts to
integrate our functionality into Moquette.

Regards

On Mon, Aug 10, 2015 at 9:23 PM, Andrea Selva notifications@github.com
wrote:

> Closed #80 https://github.com/andsel/moquette/issues/80.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/andsel/moquette/issues/80#event-378423852.

## 

William.
